apiVersion: v1
kind: PersistentVolume
metadata:
  name: registrypv
  labels: registry-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.17.0.96
    # Exported path of your NFS server and ip of server
    path: "/ocp_pv"
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: registrypvc
